const sampleListings = [
  {
    company: "TCS",
    title: "Front End Developer",
    sector: "IT",
    location: "Jaipur",
    experience: "1-5 Years",
    salary: "4-6 Lakhs P.A",
    description:
      "Front End Development | ReactJs | Javascript | CSS | Bootstrap",
    reviews: 1457,
    rating: 4.4,
    employability: "85%",
  },
  {
    company: "Google",
    title: "Software Engineer",
    sector: "IT",
    location: "Remote",
    experience: "2-6 Years",
    salary: "$150,000 - $250,000 annually",
    description:
      "Software Development | Python | Java | C++ | Machine Learning",
    reviews: 2000,
    rating: 4.8,
    employability: "92%",
  },
  {
    company: "Infosys",
    title: "Backend Developer",
    sector: "IT",
    location: "Bangalore",
    experience: "3-7 Years",
    salary: "8-12 Lakhs P.A",
    description: "Node.js | Express.js | MongoDB | REST APIs",
    reviews: 1800,
    rating: 4.6,
    employability: "88%",
  },
  {
    company: "Technical Department of Rajasthan",
    title: "Full Stack Developer",
    sector: "IT",
    location: "Hyderabad",
    experience: "4-8 Years",
    salary: "12-18 Lakhs P.A",
    description: "React.js | Node.js | SQL | Azure",
    reviews: 1600,
    rating: 4.7,
    employability: "90%",
  },
  {
    company: "Amazon",
    title: "Cloud Engineer",
    sector: "IT",
    location: "Pune",
    experience: "2-5 Years",
    salary: "6-10 Lakhs P.A",
    description: "AWS | DevOps | CI/CD | Docker | Kubernetes",
    reviews: 1300,
    rating: 4.5,
    employability: "83%",
  },
  {
    company: "IBM",
    title: "AI/ML Engineer",
    sector: "IT",
    location: "Chennai",
    experience: "3-6 Years",
    salary: "10-15 Lakhs P.A",
    description: "Machine Learning | Python | TensorFlow | AI Research",
    reviews: 1700,
    rating: 4.8,
    employability: "91%",
  },
  {
    company: "Accenture",
    title: "Consultant",
    sector: "Consulting",
    location: "Bangalore",
    experience: "3-6 Years",
    salary: "6-10 Lakhs P.A",
    description: "Business Consulting | Project Management | Strategy",
    reviews: 1600,
    rating: 4.2,
    employability: "81%",
  },
  {
    company: "McKinsey & Company",
    title: "Management Consultant",
    sector: "Consulting",
    location: "Mumbai",
    experience: "5-10 Years",
    salary: "15-25 Lakhs P.A",
    description: "Business Strategy | Operations | Financial Consulting",
    reviews: 2000,
    rating: 4.9,
    employability: "75%",
  },
  {
    company: "Deloitte",
    title: "Risk Consultant",
    sector: "Consulting",
    location: "Delhi",
    experience: "2-5 Years",
    salary: "8-12 Lakhs P.A",
    description: "Risk Management | Audit | Compliance | Financial Advisory",
    reviews: 1200,
    rating: 4.6,
    employability: "69%",
  },
  {
    company: "PwC",
    title: "Tax Consultant",
    sector: "Consulting",
    location: "Kolkata",
    experience: "4-8 Years",
    salary: "10-15 Lakhs P.A",
    description: "Taxation | Financial Consulting | Audit",
    reviews: 1400,
    rating: 4.5,
    employability: "65%",
  },
  {
    company: "KPMG",
    title: "Strategy Consultant",
    sector: "Consulting",
    location: "Gurgaon",
    experience: "3-7 Years",
    salary: "12-18 Lakhs P.A",
    description: "Business Strategy | Market Analysis | Consulting",
    reviews: 1700,
    rating: 4.7,
    employability: "62%",
  },
  {
    company: "EY",
    title: "Financial Consultant",
    sector: "Consulting",
    location: "Hyderabad",
    experience: "2-6 Years",
    salary: "8-14 Lakhs P.A",
    description: "Financial Advisory | Taxation | Audit",
    reviews: 1500,
    rating: 4.6,
    employability: "56%",
  },
  {
    company: "JP Morgan",
    title: "Financial Analyst",
    sector: "Finance",
    location: "Mumbai",
    experience: "2-4 Years",
    salary: "6-9 Lakhs P.A",
    description: "Financial Analysis | Excel | Financial Modeling",
    reviews: 1100,
    rating: 4.5,
    employability: "82%",
  },
  {
    company: "Goldman Sachs",
    title: "Investment Banker",
    sector: "Finance",
    location: "Bangalore",
    experience: "3-6 Years",
    salary: "15-20 Lakhs P.A",
    description:
      "Investment Banking | Mergers & Acquisitions | Financial Modeling",
    reviews: 1400,
    rating: 4.7,
    employability: "45%",
  },
  {
    company: "Morgan Stanley",
    title: "Equity Analyst",
    sector: "Finance",
    location: "Chennai",
    experience: "2-5 Years",
    salary: "8-12 Lakhs P.A",
    description: "Equity Research | Financial Modeling | Excel",
    reviews: 1000,
    rating: 4.6,
    employability: "81%",
  },
  {
    company: "HSBC",
    title: "Risk Analyst",
    sector: "Finance",
    location: "Delhi",
    experience: "4-7 Years",
    salary: "10-14 Lakhs P.A",
    description: "Risk Management | Compliance | Financial Analysis",
    reviews: 1200,
    rating: 4.4,
    employability: "77%",
  },
  {
    company: "Citi",
    title: "Credit Analyst",
    sector: "Finance",
    location: "Pune",
    experience: "3-6 Years",
    salary: "9-13 Lakhs P.A",
    description: "Credit Analysis | Risk Management | Financial Modeling",
    reviews: 1100,
    rating: 4.5,
    employability: "79%",
  },
  {
    company: "Barclays",
    title: "Treasury Analyst",
    sector: "Finance",
    location: "Kolkata",
    experience: "2-5 Years",
    salary: "7-10 Lakhs P.A",
    description: "Treasury Management | Risk Management | Financial Analysis",
    reviews: 1300,
    rating: 4.3,
    employability: "73%",
  },
  {
    company: "Bayer",
    title: "Agronomist",
    sector: "Agriculture",
    location: "Hyderabad",
    experience: "2-5 Years",
    salary: "6-9 Lakhs P.A",
    description: "Crop Management | Soil Science | Irrigation",
    reviews: 900,
    rating: 4.2,
    employability: "67%",
  },
  {
    company: "Syngenta",
    title: "Agricultural Engineer",
    sector: "Agriculture",
    location: "Jaipur",
    experience: "3-6 Years",
    salary: "7-10 Lakhs P.A",
    description:
      "Agricultural Machinery | Irrigation Systems | Crop Management",
    reviews: 1000,
    rating: 4.5,
    employability: "75%",
  },
  {
    company: "DuPont",
    title: "Plant Scientist",
    sector: "Agriculture",
    location: "Pune",
    experience: "4-8 Years",
    salary: "8-12 Lakhs P.A",
    description: "Plant Breeding | Genetics | Crop Management",
    reviews: 950,
    rating: 4.6,
    employability: "80%",
  },
  {
    company: "Monsanto",
    title: "Farm Manager",
    sector: "Agriculture",
    location: "Delhi",
    experience: "5-10 Years",
    salary: "10-14 Lakhs P.A",
    description: "Farm Management | Crop Production | Agricultural Economics",
    reviews: 800,
    rating: 4.4,
    employability: "69%",
  },
  {
    company: "Cargill",
    title: "Food Scientist",
    sector: "Agriculture",
    location: "Bangalore",
    experience: "3-7 Years",
    salary: "8-12 Lakhs P.A",
    description: "Food Safety | Quality Control | Research",
    reviews: 850,
    rating: 4.3,
    employability: "72%",
  },
];

module.exports = { data: sampleListings };
